# Generated by Django 3.0 on 2019-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_ID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('last_push_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('stars', models.PositiveIntegerField()),
            ],
        ),
    ]
