# Generated by Django 3.0 on 2019-12-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_display_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrecord',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='githubrecord',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='githubrecord',
            name='repository_ID',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='githubrecord',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
